package conversion;

import model.Trial;

public class BatchExporter {
    private static boolean AUTO_EXPORT = false;

    String createBatch(Trial trial) {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("3DSSPPBATCHFILE #\n");
        stringBuilder.append("COM Generated by Batchmaker. #\n");
        stringBuilder.append("AUT " + (AUTO_EXPORT ? "1" : "0") + " #\n");

        // TODO: Anthropometry.
        //stringBuilder.append()



        return stringBuilder.toString();
    }
}
